name       : haskell-hgettext
version    : 0.1.30
release    : 1
source     :
    - http://hackage.haskell.org/package/hgettext-0.1.30/hgettext-0.1.30.tar.gz : 26453a4d359c99c41d462db9f8c9144d172523b3fa7076117a877e6c43f3ffdd
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bindings to libintl.h (gettext, bindtextdomain)
description: |
    Bindings to libintl.h (gettext, bindtextdomain)
builddeps  :
    - haskell-cabal-install
    - haskell-setlocale
    - haskell-src-exts
    - haskell-uniplate
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
