name       : haskell-hgettext
version    : 0.1.31.0
release    : 4
source     :
    - http://hackage.haskell.org/package/hgettext-0.1.31.0/hgettext-0.1.31.0.tar.gz : d51fb618f414441f573d96c1bc41fcec80976a4a80453d571683cf49e57df368
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bindings to libintl.h (gettext, bindtextdomain)
description: |
    Bindings to libintl.h (gettext, bindtextdomain)
builddeps  :
    - haskell-cabal-install
    - haskell-setlocale-devel
    - haskell-src-exts-devel
    - haskell-uniplate-devel
rundeps    :
    - devel :
        - haskell-setlocale-devel
        - haskell-src-exts-devel
        - haskell-uniplate-devel
networking : yes
setup      : |
    sed -i "s|<4.11|< 4.13|g" hgettext.cabal # base
    sed -i "s|2.0.*|2.4.*|g" hgettext.cabal   # cabal
    sed -i "s|<0.6|< 0.7|g" hgettext.cabal   # containers
    sed -i "s|<1.21|<1.24|g" hgettext.cabal   # src-exts
    %patch -p1 < $pkgfiles/16.patch
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
