name       : haskell-hgettext
version    : 0.1.31.0
release    : 2
source     :
    - http://hackage.haskell.org/package/hgettext-0.1.31.0/hgettext-0.1.31.0.tar.gz : d51fb618f414441f573d96c1bc41fcec80976a4a80453d571683cf49e57df368
license    : BSD-3-Clause
component  : programming.haskell
summary    : Bindings to libintl.h (gettext, bindtextdomain)
description: |
    Bindings to libintl.h (gettext, bindtextdomain)
builddeps  :
    - haskell-cabal-install
    - haskell-setlocale
    - haskell-src-exts
    - haskell-uniplate
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
